Add compatibility for Django 4.1
jazzband/wagtailmenus pull request #429
Opened 2022-09-22 23:06 UTC by jnpkr

`django.utils.safestring.mark_safe` [now preserves lazy objects in version 4.1+](https://docs.djangoproject.com/en/4.1/releases/4.1/#utilities) so this commit sets the `mark_safe_lazy` function conditionally for compatibility

2022-09-29 10:52 UTC, janbaykara commented
Thanks for this @jnpkr. Could @ababic or @MrCordeiro review and merge this in? Very simple PR!

2022-09-29 12:27 UTC, MrCordeiro commented
Hi @jnpkr and @janbaykara!

I just have a few requests

- [ ] @jnpkr, please add yourself as a contributor (according to https://wagtailmenus.readthedocs.io/en/stable/contributing/index.html#what-your-pull-request-should-include)
- [ ] Could you modify the tox file so that the test covers Django 4.1? That would make the coverage check green again.
- [ ] Once the Django 4.1 tests are ok, add it as a compatible version on the README (I can update the CHANGELOG later when it's time to publish it)

2022-09-29 12:29 UTC, MrCordeiro requested changes
Hi @jnpkr and @janbaykara!

I just have a few requests

- [ ] @jnpkr, please add yourself as a contributor (according to https://wagtailmenus.readthedocs.io/en/stable/contributing/index.html#what-your-pull-request-should-include)
- [ ] Could you modify the tox file so that the test covers Django 4.1? That would make the coverage check green again.
- [ ] Once the Django 4.1 tests are ok, add it as a compatible version on the README (I can update the CHANGELOG later when it's time to publish it)

2022-10-15 09:35 UTC, MrCordeiro commented
Since this was solved by #432, so I'm closing this one

2022-10-15 09:35 UTC, closed without merging