Fix/settings panel append
jazzband/wagtailmenus pull request #441
Opened 2023-01-01 17:30 UTC by benfroelich

see [issue 440](https://github.com/jazzband/wagtailmenus/issues/440)

Changes to docs/source/contributing/index.rst are cosmetic and not related; I can revert if desired. I thought it was easier to read this way using shell expansion.

2023-01-01 17:36 UTC, benfroelich commented
when running tests there are several build failures related to incompatible django/wagtail versions, e.g. `wagtail 2.15 depends on Django<3.3 and >=3.0` when I run `tox -e py310-dj41-wt215` these show up in travis as `coverage not allowed` unfortunately.

2023-05-09 09:24 UTC, MrCordeiro requested changes
Hey, Ben sorry for the delay ＞︿＜

I find your PR pretty complete. It's great, thanks!

The only thing I ask is for you to rebase your fork so that we get rid of merge conflicts.

2023-06-22 00:24 UTC, djch commented
If this fixes the remaining WARNINGs, I'd be glad to see this merged!

```
wagtailmenus.FlatMenu: (wagtailadmin.W002) FlatMenu.content_panels will have no effect on modeladmin editing
        HINT: Ensure that FlatMenu uses `panels` instead of `content_panels`or set up an `edit_handler` if you want a tabbed editing interface.
There are no default tabs on non-Page models so there will be no Content tab for the content_panels to render in.
wagtailmenus.FlatMenu: (wagtailadmin.W002) FlatMenu.settings_panels will have no effect on modeladmin editing
        HINT: Ensure that FlatMenu uses `panels` instead of `settings_panels`or set up an `edit_handler` if you want a tabbed editing interface.
There are no default tabs on non-Page models so there will be no Settings tab for the settings_panels to render in.
wagtailmenus.MainMenu: (wagtailadmin.W002) MainMenu.content_panels will have no effect on modeladmin editing
        HINT: Ensure that MainMenu uses `panels` instead of `content_panels`or set up an `edit_handler` if you want a tabbed editing interface.
There are no default tabs on non-Page models so there will be no Content tab for the content_panels to render in.
wagtailmenus.MainMenu: (wagtailadmin.W002) MainMenu.settings_panels will have no effect on modeladmin editing
        HINT: Ensure that MainMenu uses `panels` instead of `settings_panels`or set up an `edit_handler` if you want a tabbed editing interface.
There are no default tabs on non-Page models so there will be no Settings tab for the settings_panels to render in.
```

2023-06-24 17:48 UTC, MrCordeiro approved these changes
LGTM!
Nice work, @benfroelich!

2023-06-24 17:48 UTC, merged